### ISSUE TITLE
Deploying Contracts on Sei rather than Osmosis

### ISSUE THREAD

**Issue by nimapourjafar** [osmosis-labs/beaker#117]
Wondering how it's possible to use beaker toolchain for Sei deployment rather than Osmosis and how to configure chain for it. 

Sei docs for reference: https://docs.seinetwork.io/smart-contracts-and-local-development/sei-tool-guide

**Comment by iboss-ptk** [comment]
So for `Beaker.toml` by default [this is what it is implied](https://github.com/osmosis-labs/beaker/tree/main/docs/config). But you can chnage any of them in your own `Beaker.toml` and these are the things you might primarily wants to change.

```toml
name = ''
gas_price = '0.025uosmo'
gas_adjustment = 1.3
account_prefix = 'osmo'
derivation_path = '''m/44'/118'/0'/0/0'''
[networks.local]
chain_id = 'localosmosis'
network_variant = 'Local'
grpc_endpoint = 'http://localhost:9090'
rpc_endpoint = 'http://localhost:26657'

[networks.testnet]
chain_id = 'osmo-test-4'
network_variant = 'Shared'
grpc_endpoint = 'https://grpc-test.osmosis.zone:443'
rpc_endpoint = 'https://rpc-test.osmosis.zone:443'

[networks.mainnet]
chain_id = 'osmosis-1'
network_variant = 'Shared'
grpc_endpoint = 'https://grpc.osmosis.zone:9090'
rpc_endpoint = 'https://rpc.osmosis.zone:443'
```

I'm open for idea like, making multiple base configs and able to do:

```toml
base = "osmosis"
```
or

```toml
base = "sei"
```

contributions are welcome.
