### ISSUE TITLE
Wasm proposal.yml

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/beaker#48]
Submitting a proposal is currently done this way:

```sh
beaker wasm proposal store-code --title "Testnet Contract" --description "Testnet Contract" --signer-account test1 --network testnet counter --gas 25000000uosmo --gas-limit 25000000
```
- We should be able hardcode maximum gas (In mainnet this won't be more than 1 OSMO)

I think we could simplify this by making a yaml file instead or json. This will be really useful as the description can be quite long. 

```
beaker wasm proposal store-code --proposal proposal_407.yaml counter
```

Example proposal.yml idea

```yml
title: Proposal to allow DappName to be enabled in Osmosis
description: |
            A lengthy proposal description
            goes here  
            we expect this to be many lines...
code:
    github:   https://github.com/osmosis-labs/beaker/
    reviewed_by: https://....
settings: 
    gas:  25000000uosmo 
    network: testnet
```

### Notes
- create struct that has all proposal options
- make the struct subcommand compatible and serde serializable
- allow serialization for toml, yaml
- put the `code` part as a metadata structure in the proposal description
